djwiki/urls.py
from django.conf.urls.defaults import *
from django.contrib.comments.models import FreeComment

urlpatterns = patterns('',
     (r'^accounts/login/$', 'django.contrib.auth.views.login'),  
     (r'^accounts/logout/$', 'django.contrib.auth.views.logout'),
     (r'^admin/', include('django.contrib.admin.urls')),
     (r'^wiki/', include('djwiki.wiki.urls')),
     (r'^comments/postfree/', 'views.my_post_free_comment'),
     (r'^comments/', include('django.contrib.comments.urls.comments')),
     (r'^xmlrpc/$', 'djwiki.wiki.xmlrpc.rpc_handler'),
)

djwiki/wiki/urls.py
from django.conf.urls.defaults import *
from tagging.views import tagged_object_list
from wiki.models import WikiPageTitle, WikiPageContent
from django.contrib.comments.models import FreeComment
from djwiki import settings


urlpatterns = patterns('django.views.generic.simple',
  (r'^list/$','direct_to_template', {'template':'wiki/pages_list.html',
                                     'extra_context': {'title':'Pages list', 
                                                       'list' : WikiPageTitle.objects.all()}}),
  (r'^$', 'redirect_to', {'url': '/wiki/home/'}),
)

urlpatterns += patterns('',
  (r'^tagcloud/$', 'djwiki.wiki.views.tagcloud'),
  (r'^register/$', 'djwiki.wiki.views.register_user'),
  (r'^permissions/$', 'djwiki.wiki.views.view_permissions'),
  (r'^addgroup/$', 'djwiki.wiki.views.add_group'),
  (r'^editgroup/$', 'djwiki.wiki.views.edit_group'),
  (r'^pagesfortag/$', 'djwiki.wiki.views.pagesfortag'),
  (r'^categories/$', 'djwiki.wiki.views.view_category'),
  (r'^upload/$','djwiki.wiki.views.upload_page'),
  (r'^upload/successful/$','djwiki.wiki.views.upload_done_page'),
  (r'^(?P<page_title>[^/]+)/$', 'djwiki.wiki.views.view_page', {'rev':0,'is_head':True}),
  (r'^(?P<page_title>[^/]+)/edit/$', 'djwiki.wiki.views.edit_page'),  
  (r'^(?P<page_title>[^/]+)/create/$', 'djwiki.wiki.views.create_page'),
  (r'^(?P<page_title>[^/]+)/rev/$', 'djwiki.wiki.views.view_revisions'),
  (r'^(?P<page_title>[^/]+)/rev/(?P<rev>\d+)/$', 'djwiki.wiki.views.view_page', {'is_head':False}),
  (r'^(?P<page_title>[^/]+)/diff/$', 'djwiki.wiki.views.diff_page'),
  (r'^static/(?P<type>[^/]*)/(?P<page>[^/]*)/(?P<file>[^/]*)/$', 'djwiki.wiki.views.view_file'),
  (r'^dynamic/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)




djwiki/wiki/models.py
from django.db import models
from tagging.models import Tag
from tagging.fields import TagField
import datetime
import tagging
from django.contrib.auth.models import Group

class WikiPageTitle(models.Model):
  title = models.CharField(max_length=100, unique=True)
  head_revision = models.IntegerField(default=0)

  def headRevisionContent(self):
        return WikiPageContent.objects.get(title=self,revision=self.head_revision)

  class Admin:
    pass
  def __unicode__(self):
    return self.title
  

class WikiPageContent(models.Model):
  title = models.ForeignKey(WikiPageTitle)
  content = models.TextField()
  author = models.CharField(max_length=100)
  revision = models.IntegerField(default=0)
  modificationTime = models.DateTimeField(auto_now_add=True) 
  markupType = models.CharField(max_length=100)
  tags = TagField()
  class Meta:
    unique_together = ("title", "revision")

  class Admin:
    pass

  def __unicode__(self):
    return self.title.title + " rev " + str(self.revision)      

  def prev_revision(self):
   if(self.revision > 0):
     return self.revision - 1
   else:
     return self.revision

  def next_revision(self):
   if(self.revision < self.title.head_revision):
     return self.revision + 1
   else:
     return self.revision
  def get_absolute_url(self):
    return ("/wiki/%s/rev/%d/" % (self.title,self.revision))
  class Meta:
        permissions = (
            ("can_view", "Can view"),
            ("can_edit", "Can edit"),
            ("can_use_xmlrpc", "Can use xml-rpc"),
        )

class WikiCategory(models.Model):
  title = models.CharField(max_length=100, unique=True)
  tags = TagField()

  class Admin:
    pass

  def __unicode__(self):
    return self.title      

class UploadedFile(models.Model):
  name = models.CharField(max_length=100)
  page = models.ForeignKey(WikiPageTitle)
  data = models.TextField()
  type = models.CharField(max_length=100)

  class Admin:
    pass

  def path(self):
    return self.page.title + '/' + self.name

  def __unicode__(self):
    return self.path()      

  class Meta:
    unique_together = ("name", "page", "type")
    permissions = (
            ("can_upload", "Can upload"),
        )

class GroupManager (models.Model):
  group = models.IntegerField()
  subgroup = models.IntegerField()
  class Meta:
    unique_together = ("group", "subgroup")
    permissions = (
            ("can_manage", "Can manage permissions"),
        )
  class Admin:
    pass
  def __unicode__(self):
    return "group " + Group.objects.get(id=self.group).name + " subgroup " + Group.objects.get(id=self.subgroup).name      


class GroupBasePerm (models.Model):
  group_id = models.IntegerField()
  permission_id = models.IntegerField()
  class Meta:
    unique_together = ("group_id", "permission_id")
  class Admin:
    pass


djwiki/wiki/views.py
from djwiki.wiki.models import *
from django.shortcuts import render_to_response, get_object_or_404
from django.views.generic.create_update import *
from django.http import Http404, HttpResponse, HttpResponseRedirect
from djwiki.wiki.myforms import *
from djwiki.settings import MEDIA_ROOT 
from tagging.models import Tag
from tagging.views import tagged_object_list
from tagging.utils import get_tag
from tagging.utils import calculate_cloud
from djwiki.wiki.diff import TextDiff
from base64 import b64encode, b64decode
from os import mkdir, remove
import os.path 
from djwiki import settings
from django.contrib.auth.decorators import login_required
from django import template
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import Permission
from djwiki.wiki.models import GroupManager

from django.contrib.comments.views.comments import post_free_comment
from django.http import HttpResponseRedirect

lastUserID=[]
lastUserID.append(str(1))

def get_user_name (request):
  if request.user == None or request.user.username=='':
     return 'Anonymous'
 
  if request.user.first_name:
    if request.user.last_name:
      return "%s %s" % (request.user.first_name, request.user.last_name)        
    else: 
      return request.user.first_name
  else:
    return request.user.username
 

def my_post_free_comment(request):
        if request.has_key('url') and not request.has_key('preview'):
                response = post_free_comment(request)
                
                # Check there's a url to redirect to, and that post_free_comment worked
                if len(request['url'].strip()) > 0 and isinstance(response, HttpResponseRedirect):
                        return HttpResponseRedirect(request['url'])
                
                # Fall back on the default post_free_comment response
                return response
        
        return post_free_comment(request)

#----------------------------------------------------------------------------------------------------------
def tags_list(request, page_title='home'):
  list = tagged_object_list(request,WikiPageContent,'hi')
  #cloud = calculate_cloud('hi')
  try:
    page_list = WikiPageTitle.objects.all();
  except:
    return HttpResponseRedirect("/wiki/%s/create/" % page_title)
  return render_to_response('wiki/tags_list.html', 
    {'pages_list' : WikiPageTitle.objects.all(),
     'count' :0,
     'pages_content' : WikiPageContent.objects.all(),
      'list' : list},
        context_instance=template.RequestContext(request))

#----------------------------------------------------------------------------------------------------------
def tagcloud(request):
  return render_to_response('wiki/tagcloud.html',{},
                        context_instance=template.RequestContext(request)) 

#----------------------------------------------------------------------------------------------------------
def pagesfortag(request):
  if 'f' in request.GET:
    param = request.GET['f']
    return render_to_response('wiki/pagesfortag.html', 
           {'tag': param},
        context_instance=template.RequestContext(request))
  else:
    raise Http404
#----------------------------------------------------------------------------------------------------------
def view_category(request):
  if 'f' in request.GET:
    param = request.GET['f']
  else:
    param = 'Main'

  category, created = WikiCategory.objects.get_or_create(title = param)  
  tag, created = Tag.objects.get_or_create(name=param)
  if request.method == 'GET':
    categoryForm = CreateCategoryForm()  
    return render_to_response('wiki/view_category.html', 
             {'tag' : tag,'form' : categoryForm},
                context_instance=template.RequestContext(request))
  elif request.method == 'POST':
    categoryForm = CreateCategoryForm(request.POST.copy())
    try:
      cat = WikiCategory.objects.get(title = categoryForm.data['Name'])
      alreadyExistsErrorMsg = [unicode("Category with this name is already exists")]
      categoryForm.errors['Name'] = alreadyExistsErrorMsg
      return render_to_response('wiki/view_category.html', 
           {'tag' : tag,'form' : categoryForm},
                context_instance=template.RequestContext(request))
    except:
      cat = WikiCategory.objects.create(title = categoryForm.data['Name'])  
      Tag.objects.add_tag(cat, param)
      return render_to_response('wiki/view_category.html', 
           {'tag' : tag,'form' : categoryForm},
           context_instance=template.RequestContext(request))

#----------------------------------------------------------------------------------------------------------
def register_user(request):
  if request.method == 'GET':
    if request.user is None or request.user.username=="":
      regForm = UserRegistrationForm()  
      register = "1"
    else:
      regForm = UserParamForm(initial={'username': request.user, 
        'pass1':"bad_pass", 'pass2':"bad_pass", 'firstName':request.user.first_name,
        'secondName':request.user.last_name, 'email':request.user.email})  
      register = ""
    return render_to_response('registration/register.html', 
             {'form' : regForm, 'register' : register},
                context_instance=template.RequestContext(request))
  elif request.method == 'POST':
    regForm = UserRegistrationForm(request.POST.copy())
    name = regForm.data['username'];
    useremail = regForm.data['email'];
    pass1 = regForm.data['pass1'];
    pass2 = regForm.data['pass2'];
    firstName = regForm.data['firstName']
    secondName = regForm.data['secondName']
    try:
      user = User.objects.get(username=name);
      if request.user is None:
          regForm.errors['username'] = [unicode("User with this name already exists")]
    except:
      user = None
    if useremail=='' or pass1 == '':
        return render_to_response('registration/register.html', 
           {'form' : regForm},
           context_instance=template.RequestContext(request))
    if pass1==pass2 and user is None:
            user = User.objects.create_user(name,useremail,pass1)
            user.first_name = firstName
            user.last_name = secondName
            user.save()
            user = authenticate(username=name, password=pass1)
            if user.is_active:
                login(request, user)
            return HttpResponseRedirect('/wiki/home')
    elif pass1==pass2:
        user.first_name = firstName
        user.last_name = secondName
        user.email = useremail
        if pass1=="bad_pass":
           pass2=pass1
        else:
           print(pass1)
           user.set_password(pass1)
        user.save()
        return HttpResponseRedirect('/wiki/home')       
    else:
        regForm.errors['pass2'] = [unicode("Passwords doesn't match each other")]
        return render_to_response('registration/register.html', 
           {'form' : regForm},
           context_instance=template.RequestContext(request))

    
#----------------------------------------------------------------------------------------------------------
def view_page(request, page_title, rev, is_head):
  try:
    pageTitle = WikiPageTitle.objects.get(title=page_title)
    if str(pageTitle.head_revision) == rev and not is_head:
      return HttpResponseRedirect("/wiki/%s/" % page_title)
    else:
      if is_head:
        page = pageTitle.headRevisionContent() 
      else:
        page = WikiPageContent.objects.get(title=pageTitle, revision=rev)
      try:
        old_content = WikiPageContent.objects.get(title=pageTitle, revision=page.revision-1).content
        diff_content = TextDiff(old_content, page.content).getDiff()
      except:
        diff_content = ''
  except:
    return HttpResponseRedirect("/wiki/%s/create/" % page_title)
  return render_to_response('wiki/view_page.html', {'page': page, 'pageTitle' : pageTitle, 'diff_content':diff_content,
                                                   'user':request.user, 'username':get_user_name(request)},
                        context_instance=template.RequestContext(request))

#----------------------------------------------------------------------------------------------------------
def create_page(request, page_title):
  view_conflict = False
  diff_content = ""

  if request.method == 'GET':
    try:
      pageTitle = WikiPageTitle.objects.get(title=page_title)
      page = WikiPageContent.objects.get(title=pageTitle, revision=pageTitle.head_revision)
    except:
      pageTitle = WikiPageTitle()
      pageTitle.title = page_title
      editForm = WikiEditForm(initial={'revision': pageTitle.head_revision, 'title' : pageTitle.title,
                                        'author':get_user_name(request)})
    else:
      return HttpResponseRedirect("/wiki/%s/" % page_title)

  elif request.method == 'POST':

    editForm = WikiEditForm(request.POST.copy())
    pageTitle, created = WikiPageTitle.objects.get_or_create(title = page_title)  
    
    if editForm.data['save_anyway'] == 'true' and not created:
      pageTitle.head_revision = pageTitle.head_revision + 1
    elif not created:
      editForm.errors['title'] = [unicode("Someone has changed this page. Unable to save this version.")]
      view_conflict = True
      diff_content = TextDiff(pageTitle.headRevisionContent().content, editForm.cleaned_data['content']).getDiff()

    if editForm.is_valid():
      page = editForm.save(commit=False) 
      page.revision = pageTitle.head_revision
      page.title = pageTitle
      pageTitle.save()
      page.save()
      return HttpResponseRedirect("/wiki/%s/" % pageTitle.title)

  return render_to_response('wiki/edit_page.html', {'form': editForm, 'title':'Create a new page', 

djwiki/templates/wiki/add_group.html
{% extends "base.html" %}

{% block title %}Permissions {% endblock %}


{% block content %}

  <SCRIPT language="JavaScript">
    function delete_group()
    {
        var isConfirmed = confirm("You are going to remove current group!\r\n");
        if(isConfirmed)
        {
          document.form.delete.value = "delete";
          document.form.submit();
        }
    }
  </SCRIPT> 


  <hr/><br/>
  <h1>{{title}}</h1>
  <br/>

  {%if perms.wiki.can_manage %}
    <form method="post" action="" name="form">
        <table> {{ form.as_table }} </table>
        <input type="hidden" name="delete" value="update" onclick="document.Delete.value='qqqqqq';"  onmouseover="fun1();"  id="id_Delete_0" />      
        <input type="submit" align="left" value="Apply" class="default"/>
        <input type="button" align="left" value="Cancel" onclick="location.href='/wiki/home/'"/> 
        <br/><br/>
        <tr><th><label for="id_Groups_0">Groups:</label></th><td><ul>
        {% for choice in groupChoices %}
          <li><label><input {% ifequal  choice.2 "1" %} checked="checked" {% endifequal %} type="checkbox" name="Groups" value="{{choice.0}}" id="id_Groups_0" /> {{choice.1}} </label></li>
        {% endfor %}
        </ul></td></tr>  
        <tr><th><label for="id_Permissions_0">Permissions:</label></th><td><ul>
        {% for choice in permsChoices %}
          <li><label><input {% ifequal  choice.2 "1" %} checked="checked" {% endifequal %} type="checkbox" name="Permissions" value="{{choice.0}}" id="id_Permissions_0" /> {{choice.1}} </label></li>
        {% endfor %}
        </ul></td></tr>
    </form>
  {% else %}
     <h1> You can not manage permissions </h1>
  {% endif %}
{% endblock %}

djwiki/templates/wiki/create_page.html
{% extends "base.html" %}

{% block content %}
<h1>Create a new page</h1>
{{ request}}
<form method="post" action="">
  <table>{{ form.as_table }}</table>
  <input type="submit" value="save" class="default"/>
  <input type="button" value="discard" onclick="history.back()"/>
</form>

{% endblock %}

djwiki/templates/wiki/diff_page.html
{% extends "base.html" %}

{% load markdown_text %}
{% load mediawiki_text %}


{% block title %}wiki page{% endblock %}

{% block content %}
 
    <h1>{{ rev1.title }}</h1>
    <hr/> 

    <div id="diff page">
    
    <h3>rev{{rev1.revision}} diff rev{{rev2.revision}}</h3>
     
    <hr/>

    <div class="content">
       {{ diff_content|safe }}
    </div>

    </div>

    
    <hr/><br/>

   <input type="button" value="back" onclick="history.back()"/>

{% endblock %}




djwiki/templates/wiki/edit_group.html
{% extends "base.html" %}

{% block title %}Permissions {% endblock %}


{% block content %}

  <SCRIPT language="JavaScript">
    function delete_group()
    {
        var isConfirmed = confirm("You are going to remove current group!\r\n");
        if(isConfirmed)
        {
          document.form.delete.value = "delete";
          document.form.submit();
        }
    }
  </SCRIPT> 


  <hr/><br/>
  <h1>{{title}}</h1>
  <br/>

  {%if perms.wiki.can_manage %}

    {%if not groupChoices %}
      There is no groups yet! <br><br></td></tr>
    {% endif %}
  

    <form method="post" action="" name="form">
      {%if groupChoices %}
        <table> {{ form.as_table }} </table>
        <input type="hidden" name="delete" value="update" onclick="document.Delete.value='qqqqqq';"  onmouseover="fun1();"  id="id_Delete_0" />      
        <input type="submit" align="left" value="Update" class="default"/>
      {%endif%}

      {%if not groupChoices%}
        <input type="button" align="left" value="AddGroup" onclick="location.href='/wiki/addgroup/'"/> 
        <br/><br/>
      {% endif %}
      {%if groupChoices %}
        <input type= "button" onClick="javascript: delete_group();" value= "Delete current group">
        <input type= "button" onClick="location.href='/wiki/addgroup/'" value= "Create new group">
      {%endif%}
      <input type="button" align="left" value="Cancel" onclick="location.href='/wiki/home/'"/> 
      {% if groupChoices %}
        <br/><br/>
        <tr><th><label for="id_Groups_0">Groups:</label></th><td><ul>
        {% for choice in groupChoices %}
          <li><label><input {% ifequal  choice.2 "1" %} checked="checked" {% endifequal %} type="checkbox" name="Groups" value="{{choice.0}}" id="id_Groups_0" /> {{choice.1}} </label></li>
        {% endfor %}
        </ul></td></tr>  
        <tr><th><label for="id_Permissions_0">Permissions:</label></th><td><ul>
        {% for choice in permsChoices %}
          <li><label><input {% ifequal  choice.2 "1" %} checked="checked" {% endifequal %} type="checkbox" name="Permissions" value="{{choice.0}}" id="id_Permissions_0" /> {{choice.1}} </label></li>
        {% endfor %}
        </ul></td></tr>
      {%endif%}
    </form>
  {% else %}
     <h1> You can not manage permissions </h1>
  {% endif %}
{% endblock %}

djwiki/templates/wiki/pages_list.html
{% extends "base.html" %}

{% block title %}wiki page{% endblock %}

{% block content %}
                      
    <hr/><br/>
    <h1>{{title}}</h1>

    {%if list%}   
        <br/>
        <table cellspacing="0">
        <tbody>
            {% for page in list %}
              <tr class="{% cycle 'row1' 'row2' %}">
                <th scope="col"><a href="../{{page.title}}"> {{ page.title }}  {{Index}}</a></th>
                <th scope="col">Head rev No: {{page.head_revision}}</th>
                <th scope="col">Auth: {{page.headRevisionContent.author}}</th>
                <th scope="col">Modificated: {{page.headRevisionContent.modificationTime|date:"jS F Y H:i:s"}}</th>
              </tr> 
            {% endfor %}
        </tbody></table>
    {%else%}
        No pages yet
    {%endif%}

{% endblock %}

djwiki/templates/wiki/perm_list.html
{% extends "base.html" %}

{% block title %}Permissions {% endblock %}

{% block content %}
    <hr/><br/>
    <h1>{{title}}</h1>
    <br/>

  {%if perms.wiki.can_manage %} 

    <form method="post" action="" name="form">
      <tr><th><label for="id_User_0">User:</label></th><td>
        {{ form.User }}
      </td></tr><br><br>

      <tr><th><label for="id_Groups_0">Groups:</label></th><td><ul>
      {% for choice in groupChoices %}
        <li><label><input {% ifequal  choice.2 "1" %} checked="checked" {% endifequal %} type="checkbox" name="Groups" value="{{choice.0}}" id="id_Groups_0" /> {{choice.1}} </label></li>
      {% endfor %}
      </ul></td></tr>

      <tr><th><label for="id_Permissions_0">Permissions:</label></th><td><ul>
      {% for choice in permsChoices %}
        <li><label><input {% ifequal  choice.2 "1" %} checked="checked" {% endifequal %} type="checkbox" name="Permissions" value="{{choice.0}}" id="id_Permissions_0" /> {{choice.1}} </label></li>
      {% endfor %}
      </ul></td></tr>

      <input type="submit" align="left" value="Apply" class="default"/>
      <input type="button" align="left" value="cancel" onclick="location.href='/wiki/home/'"/> 
    </form>

  {% else %}
     <h1> You can not manage permissions </h1>
  {% endif %}


{% endblock %}

djwiki/templates/wiki/rev_list.html
{% extends "base.html" %}

{% block title %}wiki page{% endblock %}

{% block content %}
                      
    <hr/><br/>
    <h1>{{title}}</h1>
    <br/>

    <form method="post" action="">

    <table>{{ form.as_table }}</table>

    <table cellspacing="0">
    <thead><tr>
      <th class="sorted ascending"></th>
      <th>Revison</th>
      <th>Author</th>
      <th>Modificated</th>
      <th>Tags</th>
      <th>Content</th>
    </tr></thead>
    
    <tbody>
      {%if errors%}
      <ul class="errorlist"><li>{{errors}}</li></ul>
      {%endif%}
      {% for rev in revisions %}
      <tr class="{% cycle 'row1' 'row2' %}">
        <th><label><input type="checkbox" name="Revisions" value="{{rev.0}}" id="id_Revisions_{{rev.0}}" /></label></th>
        <td><a href="./{{rev.0}}"> rev {{rev.0}}</a></td>
        <td>{{rev.1}}</td>
        <td>{{rev.2|date:"jS F Y H:i:s"}}</td>
        <td>{{rev.3|safe}}</td>
        <td>{{rev.4|safe}}</td>
      </tr>
      {% endfor %}
    </tbody></table>

      <input type="submit" align="left" value="view diff" class="default"/>
      <input type="button" align="left" value="cancel" onclick="location.href='../'"/> 
    </form> 

{% endblock %}

djwiki/templates/wiki/upload_page.html
{% extends "base.html" %}

{% block content %}
<h1>Upload page</h1>
{%if perms.wiki.add_uploadedfile%}
  <form enctype="multipart/form-data" method="post" action="">
    <table>{{ form.as_table }}</table>
  
    <input type="button" align="left" value="discard" onclick="location.href='../'"/> 
    <input type="submit" align="left" value="upload" class="default"/>
  </form>
{%else%}
  You have not enough permission to upload files
{%endif%}
  
{% endblock %}

djwiki/templates/wiki/user_attributes.html
{% extends "base.html" %}

{% load tagging_tags %}

{% block title %}wiki page{% endblock %}


{% block content %}

    
    <form method="post" action="">
        <table>{{ form.as_table }}</table>
        <input type="submit" value="Add" class="default"/>
    </form>


{% endblock %}

djwiki/templates/wiki/view_category.html
{% extends "base.html" %}

{% load tagging_tags %}

{% block title %}wiki page{% endblock %}


{% block content %}

    
    <hr/><br/>
    <h1>Category: {{tag.name}}</h1>
    <hr/>
    <h2>Subcategories: </h2>
    {% tagged_objects tag in wiki.WikiCategory as LinkedPages%}
    {{LinkedPages.sort}}
    {%if LinkedPages%}
        <table cellspacing="0">
        <tbody>
            </tr>
            {% for CurrentPage in LinkedPages %}
                <tr class="{% cycle 'row1' 'row2' %}">
                  <th scope="col"><a href="../../wiki/categories/?f={{CurrentPage.title}}"> {{ CurrentPage.title }}  </a></th>
                </tr> 
            {% endfor %}
        </tbody></table>
    {%else%}
        No subcategories here
    {%endif%}


    <br/><hr/>
    <h2>Pages: </h2>
    {% tagged_objects tag in wiki.WikiPageContent as LinkedPages%}
    {{LinkedPages.sort}}
    {%if LinkedPages%}
        <table cellspacing="0">
        <tbody>
            </tr>
            {% for CurrentPage in LinkedPages %}
                <tr class="{% cycle 'row1' 'row2' %}">
                  <th scope="col"><a href="{{CurrentPage.get_absolute_url}}"> {{ CurrentPage.title }}  </a></th>
                  <th scope="col">Head rev No: {{CurrentPage.revision}}</th>
                  <th scope="col">Auth: {{CurrentPage.author}}</th>
                  <th scope="col">Modificated: {{CurrentPage.modificationTime|date:"jS F Y H:i:s"}}</th>
                 </tr> 
            {% endfor %}
        </tbody></table>
    {%else%}
        No pages in this category
    {%endif%}

    {%if perms.wiki.add_wikicategory%}
        <br/><hr/>
        <h2>Add subcategory</h2>
        <form method="post" action="">
            <table>{{ form.as_table }}</table>
            <input type="submit" value="Add" class="default"/>
        </form>
    {%else%}
        You can not add subcategories
    {%endif%}


{% endblock %}